name: PipelineWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        name: Azure Pipeline
        runs-on: azure_linux
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/fabiodeorazi/DevProject
            azure-pipeline-name: 'webapp.git'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
